name: lint_factory
description: Dart / Flutter lint rules used internally by innFactory GmbH.
version: 3.7.0
homepage: https://github.com/innFactory/flutter_lint_factory
repository: https://github.com/innFactory/flutter_lint_factory
issue_tracker: https://github.com/innFactory/flutter_lint_factory/issues
documentation: https://github.com/innFactory/flutter_lint_factory

environment:
  sdk: ">=2.18.5 <3.0.0"
